// import Navbar from './components/Navbar'
import './globals.css'
import { GeistSans } from "geist/font/sans";
import ApplicationLogo from './components/ApplicationLogo';

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className} max-w-xl mx-auto px-4 mb-12`}>
        <ApplicationLogo />
        {children}
      </body>
    </html>
  )
}
