import './globals.css'
import { GeistSans } from "geist/font/sans";
import { Handjet } from 'next/font/google'
import ApplicationLogo from './components/ApplicationLogo';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const handjet = Handjet({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-handjet',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className} ${handjet.variable} max-w-xl mx-auto px-4 bg-white`}>
        {children}
      </body>
    </html> 
  )
}
